name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.x' # ou a versão que você está usando

      - name: Build and publish APIs
        run: |
          dotnet publish ./AloDoutor.API/AloDoutor.API.csproj -c Release -o ./publish/AloDoutor
          dotnet publish ./AloFInances/AloFinances.Api.csproj -c Release -o ./publish/AloFinances
          dotnet publish ./Identidade.API/Identidade.API.csproj -c Release -o ./publish/Identidade

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'seu-app-no-azure'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9CFC879B1409491EB61B6B15A2699C8C }}
          package: './publish'
