name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.x' # ou a versão que você está usando

      - name: Build and publish AloDoutor.API
        run: |
          cd AloDoutor.API
          dotnet publish -c Release -o ./publish
        working-directory: ${{ github.workspace }}

      - name: Build and publish AloFinances.API
        run: |
          cd AloFInances
          dotnet publish -c Release -o ./publish
        working-directory: ${{ github.workspace }}

      - name: Build and publish Identidade.API
        run: |
          cd Identidade.API
          dotnet publish -c Release -o ./publish
        working-directory: ${{ github.workspace }}

      - name: Deploy to Azure - AloDoutor.API
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'alo-identidade-agendamento'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_91A1202092234BDB96207ECFEA48C9BA }}
          package: './AloDoutor.API/publish'

      - name: Deploy to Azure - AloFinances.API
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'alo-identidade-financeiro'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_2CA862D972BD4A5583D7F15492561B83 }}
          package: './AloFInances/publish'

      - name: Deploy to Azure - Identidade.API
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'alo-identidade'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BFE303BAB8F849F98D6FA773F025787D }}
          package: './Identidade.API/publish'
